//+------------------------------------------------------------------+
//|                             EMA Crossover - Decision Tree + SLTP |
//|                                            Forex Strategy Studio |
//|                              https://www.forexstrategystudio.com |
//+------------------------------------------------------------------+
#property description "Generated by Forex Strategy Studio."
#property link        "https://www.forexstrategystudio.com"
#property version     "2.00"

input double LOTS = 0.1;

enum CLOSE_TYPE {
   SLTP = 1,
   CUSTOM_CLOSE_LOGIC = 2
};

enum SLTPType {
   NONE = 0,
   ABSOLUTE = 1,
   PERCENTAGE = 2,
   PIPS = 3
};

enum ACTION {
   STRONG_BUY   = 2,
   BUY          = 1,
   NEUTRAL      = 0,
   SELL         = -1,
   STRONG_SELL  = -2,
   NOP          = -3,
   ERROR        = -4,
   CLOSE        = -5
};

enum BAR_PART {
   BP_OPEN = 0,
   BP_HIGH = 1,
   BP_LOW = 2,
   BP_CLOSE = 3,
   BP_VOLUME = 4
};

//--- In-memory runtime state flags.
//--- Notes / limitations:
//---   * These flags are not reconstructed from terminal state; they reset on EA restart.
//---   * They assume a single net position per symbol (BUY or SELL) tracked by this EA instance.
static bool BUY_OPEN = false;
static bool SELL_OPEN = false;
static datetime last_bar_time = 0;
static double openPrice = 0.0;
static int currentIndex = 0;

//--- Exit policy configuration.
//--- The EA supports either classic SL/TP-style exit rules (implemented locally)
//--- or a placeholder hook for custom close logic (decision-tree driven).
static CLOSE_TYPE closeType = SLTP;
static SLTPType tpType = PIPS;
static SLTPType slType = PIPS;
static double tpValue = 20.0;
static double slValue = 100.0;

//+------------------------------------------------------------------+
//| Expert initialization                                            |
//+------------------------------------------------------------------+
int OnInit() {
   // This EA does not pre-create indicator handles; all indicator access is on-demand.
   // If you later add persistent handles, this is the natural place to validate inputs
   // and fail fast with INIT_FAILED.
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Per-tick event handler (bar-gated trading logic)                 |
//+------------------------------------------------------------------+
void OnTick() {

   // Bar-gating: ensures the strategy is evaluated once per bar, avoiding repeated
   // order submission on every tick (which can cause overtrading and broker rejections).
   datetime current_bar_time = iTime(_Symbol, _Period, 0);

   if(current_bar_time == last_bar_time)
      return;

   last_bar_time = current_bar_time;

   if(BUY_OPEN || SELL_OPEN) {
      // When a position is open, we only run exit logic. This prevents the decision tree
      // from opening additional positions while already exposed.
      ACTION action = decideIfClosePosition();
      if(action == ACTION::CLOSE) {
         if(closePosition()) {
            SELL_OPEN = false;
            BUY_OPEN = false;
         }
      }
      return;
   }

   // Decision-tree inputs: calcMovingAvg(period, shift, symbol, timeframe, method, applied_price).
   // This block votes BUY/SELL based on EMA(9) vs EMA(21) crossover confirmation using two shifts.
   ACTION actions0 [] = {booleanToAction(ACTION::BUY, ((calcMovingAvg(
         9,
         0,
         Symbol(),
         Period(),
         MODE_EMA,
         PRICE_CLOSE
                                         ) > calcMovingAvg(
                                               21,
                                               0,
                                               Symbol(),
                                               Period(),
                                               MODE_EMA,
                                               PRICE_CLOSE
                                         )) && (calcMovingAvg(
                                               9,
                                               3,
                                               Symbol(),
                                               Period(),
                                               MODE_EMA,
                                               PRICE_CLOSE
                                               ) < calcMovingAvg(
                                                     21,
                                                     3,
                                                     Symbol(),
                                                     Period(),
                                                     MODE_EMA,
                                                     PRICE_CLOSE
                                               )))), booleanToAction(ACTION::SELL, ((calcMovingAvg(
                                                     9,
                                                     0,
                                                     Symbol(),
                                                     Period(),
                                                     MODE_EMA,
                                                     PRICE_CLOSE
                                                     ) < calcMovingAvg(
                                                           21,
                                                           0,
                                                           Symbol(),
                                                           Period(),
                                                           MODE_EMA,
                                                           PRICE_CLOSE
                                                     )) && (calcMovingAvg(
                                                           9,
                                                           3,
                                                           Symbol(),
                                                           Period(),
                                                           MODE_EMA,
                                                           PRICE_CLOSE
                                                           ) > calcMovingAvg(
                                                                 21,
                                                                 3,
                                                                 Symbol(),
                                                                 Period(),
                                                                 MODE_EMA,
                                                                 PRICE_CLOSE
                                                           ))))
                        };

   // Aggregates node outputs into a single trading intent.
   // With ignoreNeutralSignals=true, only explicit BUY/SELL votes contribute to the result.
   ACTION action = actionAverage(actions0, true);

   switch(action) {
   case ACTION::STRONG_BUY:
   case ACTION::BUY:
      if(openPosition(ORDER_TYPE_BUY, LOTS)) {
         BUY_OPEN = true;
      }
      break;
   case ACTION::STRONG_SELL:
   case ACTION::SELL:
      if(openPosition(ORDER_TYPE_SELL, LOTS)) {
         SELL_OPEN = true;
      }
      break;
   default:
      break;
   }

}

//+-------------------------------------------------------------------+
//| Close the current symbol position (market close via opposite deal)|
//+-------------------------------------------------------------------+
bool closePosition() {

   // This EA is written for “one position per symbol” semantics. If multiple positions
   // exist (hedging), PositionSelect(_Symbol) selects the netting position (or a single
   // position depending on account type). The ticket is then used to target the close.
   if(!PositionSelect(_Symbol)) {
      Print("No position to close for symbol ", _Symbol);
      return false;
   }

   ulong position_ticket = (ulong)PositionGetInteger(POSITION_TICKET);
   double volume = PositionGetDouble(POSITION_VOLUME);
   ENUM_POSITION_TYPE pos_type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);

   if(volume <= 0.0) {
      Print("Position volume is 0 or invalid. Cannot close.");
      return false;
   }

   // MT5 closes positions by sending an opposite-side market deal.
   // For hedging accounts, request.position must be set to ensure the correct position is closed.
   MqlTradeRequest request;
   MqlTradeResult  result;
   ZeroMemory(request);

   request.action        = TRADE_ACTION_DEAL;
   request.symbol        = _Symbol;
   request.volume        = volume;
   request.position     = position_ticket;  // <-- Important for hedging accounts
   request.type_filling  = ORDER_FILLING_FOK;  // or ORDER_FILL_IOC depending on broker
   request.deviation     = 10;              // adjust as needed

   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   if(pos_type == POSITION_TYPE_BUY) {
      // Market-close a BUY using the current bid.
      request.type  = ORDER_TYPE_SELL;
      request.price = bid;
   } else if(pos_type == POSITION_TYPE_SELL) {
      // Market-close a SELL using the current ask.
      request.type  = ORDER_TYPE_BUY;
      request.price = ask;
   }

   if(!OrderSend(request, result)) {
      Print("Failed to send close order. Error: ", GetLastError());
      return false;
   }

   if(result.retcode == TRADE_RETCODE_DONE) {
      Print("Position closed successfully.");
      return true;
   } else {
      Print("Failed to close position. Retcode: ", result.retcode);
      return false;
   }
}

//+------------------------------------------------------------------+
//| Open a market position for the current symbol                    |
//+------------------------------------------------------------------+
bool openPosition(ENUM_ORDER_TYPE order_type, double lot_size) {

   MqlTradeRequest request;
   MqlTradeResult  result;
   ZeroMemory(request);

   // Market execution request. Practical failures include: unsupported filling mode,
   // insufficient margin, trading disabled, invalid volume, or price requotes.
   request.action           = TRADE_ACTION_DEAL;     // Immediate order execution
   request.symbol           = _Symbol;
   request.volume           = lot_size;
   request.type             = order_type;
   request.type_filling     = ORDER_FILLING_FOK;       // Or ORDER_FILL_IOC depending on broker
   request.deviation        = 10;                   // Max price deviation in points (adjust as needed)

   // Use the correct side of the spread for the requested direction.
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   if(order_type == ORDER_TYPE_BUY)
      request.price = ask;
   else if(order_type == ORDER_TYPE_SELL)
      request.price = bid;

   if(!OrderSend(request, result)) {
      Print("Failed to send order. Error: ", GetLastError());
      return false;
   }

   if(result.retcode == TRADE_RETCODE_DONE) {
      Print("Position opened successfully. Ticket: ", result.order, " at price: ", result.price);
      // openPrice is later used by the exit logic to compute P/L deltas.
      // It assumes this EA is the only opener of the tracked position.
      openPrice = result.price;
      return true;
   } else {
      Print("Order send failed. Retcode: ", result.retcode);
      return false;
   }
}

//+------------------------------------------------------------------+
//| Decide whether the currently tracked position should be closed   |
//+------------------------------------------------------------------+
ACTION decideIfClosePosition() {

   switch(closeType) {

   case SLTP: {

      double currentPrice = iClose(_Symbol, _Period, 0);
      bool isBuy = BUY_OPEN;
      double diff = (currentPrice - openPrice)*(isBuy ? 1 : -1);
      string currencyPair = Symbol();

      // Pip sizing heuristic used for “PIPS” TP/SL mode.
      // This is intentionally simple and may not match every symbol’s tick size/point value.
      // If you trade exotics or CFDs, consider using SymbolInfoDouble(_Symbol, SYMBOL_POINT)
      // (and/or SYMBOL_TRADE_TICK_SIZE) to compute pip distances precisely.
      double pipValue = IsSubstringIgnoreCase(currencyPair, "JPY") ? 0.01
                        : IsSubstringIgnoreCase(currencyPair, "BITCOIN") ? 0.1
                        : 0.0001;

      // The sign of diff indicates whether the trade is currently favorable (profit) or not (loss).
      // Assumes openPrice is set by openPosition(); if openPrice is 0, percentage checks would be invalid.
      if(diff > 0) {
         switch(tpType) {
         case ABSOLUTE:
            if(isBuy ? currentPrice >= tpValue : currentPrice <= tpValue) {
               return ACTION::CLOSE;
            }
            break;
         case PERCENTAGE: {
            double pctDiff = (diff/openPrice) * 100;
            if(pctDiff >= tpValue) {
               return ACTION::CLOSE;
            }
            break;
         }
         case PIPS:
            if(diff/pipValue >= tpValue) {
               return ACTION::CLOSE;
            }
            break;
         case NONE:
         default:
            break;
         }
         return ACTION::NOP;
      } else {
         switch(slType) {
         case ABSOLUTE:
            if(isBuy ? currentPrice <= slValue : currentPrice >= slValue) {
               return ACTION::CLOSE;
            }
            break;
         case PERCENTAGE: {
            double pctDiff = (-diff/openPrice) * 100;
            if(pctDiff >= slValue) {
               return ACTION::CLOSE;
            }
            break;
         }
         case PIPS:
            if((-diff/pipValue) >= slValue) {
               return ACTION::CLOSE;
            }
            break;
         case NONE:
         default:
            break;
         }
         return ACTION::NOP;
      }
      break;
   }
   case CUSTOM_CLOSE_LOGIC: {
      // Placeholder for user-defined exit logic.
      // Expected behavior: compute a "closeAction" signal (e.g., from a decision tree)
      // and close the position when it strongly contradicts the current exposure.
      ACTION closeAction = ACTION::NOP;

      if(BUY_OPEN) {
         if(closeAction == ACTION::SELL || closeAction == ACTION::STRONG_SELL) {
            return ACTION::CLOSE;
         }
      } else {
         if(closeAction == ACTION::BUY || closeAction == ACTION::STRONG_BUY) {
            return ACTION::CLOSE;
         }
      }
   }
   default:
      return ACTION::NOP;
   }
}

//+------------------------------------------------------------------+
//| Case-insensitive substring check (utility)                       |
//+------------------------------------------------------------------+
bool IsSubstringIgnoreCase(string mainString, string subString) {

   // StringToLower mutates the passed string variable. Here it is safe because strings
   // are passed by value (local copies), so the caller's originals are not modified.
   StringToLower(mainString);
   StringToLower(subString);

   return (StringFind(mainString, subString) != -1);
}

//+------------------------------------------------------------------+
//| Map an integer score to an ACTION enum                           |
//+------------------------------------------------------------------+
ACTION ActionFromValue(int value) {

   // This mapping is used to translate averaged/rounded scores back into discrete signals.
   // Any unexpected value is treated as ERROR to avoid silently producing a trade signal.
   switch(value) {
   case  2:
      return STRONG_BUY;
   case  1:
      return BUY;
   case  0:
      return NEUTRAL;
   case -1:
      return SELL;
   case -2:
      return STRONG_SELL;
   case -3:
      return NOP;
   case -4:
      return ERROR;
   case -5:
      return CLOSE;
   default:
      return ERROR;
   }

}

//+------------------------------------------------------------------+
//| Convert an arbitrary double into a discrete ACTION               |
//+------------------------------------------------------------------+
ACTION ActionFromDouble(double value) {
   // Round away fractional noise but preserve sign. This is mainly used for averages.
   int roundedValue = (int)MathRound(MathAbs(value)) * (value < 0 ? -1 : 1);
   return ActionFromValue(roundedValue);
}

//+------------------------------------------------------------------+
//| Human-readable ACTION label (logging / debugging)                |
//+------------------------------------------------------------------+
string ActionToString(ACTION action) {

   switch(action) {
   case STRONG_BUY:
      return "STRONG BUY";
   case BUY:
      return "BUY";
   case NEUTRAL:
      return "NEUTRAL";
   case SELL:
      return "SELL";
   case STRONG_SELL:
      return "STRONG SELL";
   case NOP:
      return "NOP";
   case ERROR:
      return "ERROR";
   case CLOSE:
      return "CLOSE";
   default:
      return "UNKNOWN ACTION";
   }

}

//----------------------DECISION-TREE NODES---------------------------



//+------------------------------------------------------------------+
//| Convert a boolean rule result into an ACTION vote                |
//+------------------------------------------------------------------+
ACTION booleanToAction(
   ACTION actionIfTrue,
   bool inputBool
) {
   if(inputBool) {
      return actionIfTrue;
   } else {
      return ACTION::NEUTRAL;
   }
}

//+------------------------------------------------------------------+
//| Aggregate multiple ACTION votes into a single decision           |
//+------------------------------------------------------------------+
ACTION actionAverage(const ACTION &actions[], bool ignoreNeutralSignals) {

   // Defensive aggregation: handles empty arrays and (optionally) ignores NEUTRAL votes.
   // This prevents "no signal" nodes from diluting strong consensus.

   int count = ArraySize(actions);

   // No inputs means no actionable signal.
   if(count == 0)
      return ACTION::NEUTRAL; // or any other default you prefer

   int validCount = 0;
   double sum = 0.0;
   for(int i = 0; i < count; i++) {
      // When configured, NEUTRAL acts like "abstain".
      if(ignoreNeutralSignals && actions[i] == ACTION::NEUTRAL)
         continue;
      sum += (int)actions[i]; // Cast each ACTION to its underlying integer value
      validCount++;
   }

   // If everything was neutral/ignored, keep the outcome neutral.
   if(validCount == 0)
      return ACTION::NEUTRAL;

   // Average the vote scores, then round to the nearest discrete action.
   double averageDouble = sum / validCount;

   int averageInt = (int)MathRound(averageDouble);

   return ActionFromValue(averageInt);
}

//+------------------------------------------------------------------+
//| Compute a moving average value for the requested data source     |
//+------------------------------------------------------------------+
double calcMovingAvg(
   int period,
   int shift,
   string currencyPair,
   ENUM_TIMEFRAMES timeframe,
   ENUM_MA_METHOD maMethod,
   int barPart // ENUM_APPLIED_PRICE | -1 (volume)
) {

   int handleVolumes = INVALID_HANDLE;

   if(barPart == -1) {

      // Special sentinel: barPart == -1 means "volume" in this generated EA.
      // Volume is not a standard applied-price series, so a separate handle is created.

      handleVolumes = iVolumes(currencyPair, timeframe, VOLUME_TICK);

      if(handleVolumes == INVALID_HANDLE) {
         Print("Error creating volume handle. Error code: ", GetLastError());
         return EMPTY_VALUE;
      }
   }

   int ma_handle = iMA((barPart == -1 ? NULL : currencyPair),
                       (barPart == -1 ? PERIOD_CURRENT : timeframe),
                       period,
                       0,
                       maMethod,
                       barPart == -1 ? handleVolumes : barPart);

   // Handle creation can fail due to invalid parameters, insufficient history, or terminal state.

   if(ma_handle == INVALID_HANDLE) {
      Print("Failed to create iMA handle! Error: ", GetLastError());
      if(handleVolumes != INVALID_HANDLE) {
         IndicatorRelease(handleVolumes);
      }
      return EMPTY_VALUE;
   }

   double ma_values[];

   if(CopyBuffer(ma_handle, 0, shift+1, 1, ma_values) != 1) {
      // CopyBuffer failures commonly indicate missing data (history not ready) or an invalid handle.
      Print("Failed to copy iMA buffer. Error: ", GetLastError());
      IndicatorRelease(ma_handle);
      if(handleVolumes != INVALID_HANDLE) {
         IndicatorRelease(handleVolumes);
      }
      return EMPTY_VALUE;
   }

   double result = ma_values[0];
   IndicatorRelease(ma_handle);
   if(handleVolumes != INVALID_HANDLE) {
      IndicatorRelease(handleVolumes);
   }

   // EMPTY_VALUE is returned earlier on failure; otherwise return the computed MA.
   return result;
}
//+------------------------------------------------------------------+
